#\u6838\u5FC3\u7EBF\u7A0B
spring:
  task:
    execution:
     pool:
      core-size: 8
      queue-capacity: 2000
      max-size: 16
     thread-name-prefix: vms-
  application:
    name: device
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.12.191.184:3306/vms?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: dreamcc@2020
